### ISSUE TITLE
ImportError: cannot import name 'ntid_data'，我注意到utils模块下是没有ntid_data模块的，这个问题该怎么解决，谢谢

### ISSUE THREAD

**Issue by a139122679** [bmartacho/UniPose#34]
Traceback (most recent call last):
  File "unipose.py", line 12, in <module>
    from utils.utils import get_model_summary
  File "/user3/lwx1055260/ID2463_UniPose_for_pytorch/utils/utils.py", line 8, in <module>
    from utils       import ntid_data            as ntid_data
ImportError: cannot import name 'ntid_data'

**Comment by a139122679** [comment]
Resolved, I don't use the NTID dataset, so just comment out the import module part of the code.
