### ISSUE TITLE
ValueError: too many values to unpack (expected 2) ,Hello, how can I solve this problem?

### ISSUE THREAD

**Issue by a139122679** [bmartacho/UniPose#35]
Traceback (most recent call last):
  File "unipose.py", line 270, in <module>
    trainer = Trainer(args)
  File "unipose.py", line 64, in __init__
    self.val_dir, self.sigma, self.stride, self.workers, self.batch_size)
ValueError: too many values to unpack (expected 2)

**Comment by YongSeongLee25** [comment]
utils.py

getDataloader()
return train_loader, val_loader

**Comment by Zinia17** [comment]
Hi, can any one help me about the following error?
Traceback (most recent call last):
  File "T:\unipose\unipose.py", line 276, in <module>
    trainer.training(epoch)
  File "T:\unipose\unipose.py", line 107, in training
    for i, (input, heatmap, centermap, img_path) in enumerate(tbar):
ValueError: too many values to unpack (expected 4)

**Comment by Zinia17** [comment]
Another error: 
Traceback (most recent call last):
  File "T:\unipose\unipose.py", line 279, in <module>
    trainer.training(epoch)
  File "T:\unipose\unipose.py", line 112, in training
    input_var     =     input.cuda()
AttributeError: 'int' object has no attribute 'cuda'
